message(STATUS "")

message(STATUS "HPFFT ${PROJECT_VERSION}")

string(TOUPPER "${CMAKE_BUILD_TYPE}" HPFFT_BUILD_TYPE)
set(HPFFT_OPTIONS "CMAKE_INSTALL_PREFIX;BUILD_SHARED_LIBS;CMAKE_BUILD_TYPE;CMAKE_CXX_FLAGS_${HPFFT_BUILD_TYPE};CMAKE_CXX_FLAGS;MPI_CXX_COMPILER;MPI_CXX_COMPILE_OPTIONS")

if (HPFFT_ENABLE_CUDA)
    list(APPEND HPFFT_OPTIONS "CUDA_NVCC_FLAGS")
    list(APPEND HPFFT_OPTIONS "CUDA_TOOLKIT_ROOT_DIR")
endif()

foreach(_opt CUDA HEFFTE FFTMPI ACCFFT P3DFFT FFTE SWFFT 2DECOMP NB3DFFT FFTW FFTADVMPI)
    list(APPEND HPFFT_OPTIONS "HPFFT_ENABLE_${_opt}")
endforeach()

foreach(_opt ${HPFFT_OPTIONS})
    message(STATUS " -D ${_opt}=${${_opt}}")
endforeach()
unset(_opt)

message(STATUS "")
